# Numpy Tutorial 

In [1]:
import numpy as np 

In [2]:
#  Creating a 2D numpy array with the given elements and datatype int64
myarr = np.array([[3,6,32,7]], np.int64)

In [3]:
# Accessing the element at row 0, column 1 of the array
myarr[0,1]

np.int64(6)

In [4]:
# Getting the shape of the array (number of rows, columns)
myarr.shape

(1, 4)

In [5]:
# Getting the data type of the elements in the array
myarr.dtype

dtype('int64')

In [6]:
# Modifying the element at row 0, column 1 to 45 and printing the array
myarr[0,1] = 45
myarr

array([[ 3, 45, 32,  7]])

In [7]:
# Creating a 2D numpy array from a list of lists
listarray = np.array([[1,2,3],[5,8,5],[0,3,1]])

In [8]:
# Printing the created array
listarray

array([[1, 2, 3],
       [5, 8, 5],
       [0, 3, 1]])

In [9]:
# Checking the datatype of the array elements
listarray.dtype

dtype('int64')

In [10]:
# Checking the shape of the array
listarray.shape

(3, 3)

In [11]:
# Checking the size (total number of elements) of the array
listarray.size

9

In [12]:
# Creating an array from a set, which removes duplicates
np.array({24,23,23})

array({24, 23}, dtype=object)

In [13]:
# Creating a 2x5 array filled with zeros
zeros = np.zeros((2,5))

In [14]:
# Printing the zeros array
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [15]:
# Checking the datatype of the zeros array
zeros.dtype

dtype('float64')

In [16]:
# Checking the shape of the zeros array
zeros.shape

(2, 5)

In [17]:
# Creating an array with values from 0 to 14
rng = np.arange(15)

In [18]:

# Printing the created array
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [19]:
# Creating 10 equally spaced numbers between 1 and 50
lspace = np.linspace(1,50,10)

In [20]:
# Printing the created array
lspace

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

In [21]:
# Creating an empty array with a shape of 4x6
emp = np.empty((4,6))

In [22]:
# Printing the empty array (uninitialized values)
emp 

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        3.11522054e-307, 1.42413555e-306, 1.78019082e-306],
       [1.37959740e-306, 6.23057349e-307, 1.02360935e-306,
        1.69120416e-306, 1.78022342e-306, 6.23058028e-307],
       [1.06811422e-306, 9.45699680e-308, 1.11258854e-306,
        1.11261502e-306, 1.42410839e-306, 7.56597770e-307],
       [6.23059726e-307, 1.42419530e-306, 1.78018811e-306,
        1.33511562e-306, 1.69118515e-306, 9.34607074e-307]])

In [23]:
# Creating an empty array with the same shape as lspace
emp_l = np.empty_like(lspace)

In [24]:
# Printing the empty_like array
emp_l

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

In [25]:
# Creating an identity matrix of size 45x45
ide = np.identity(45)

In [26]:
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [27]:
# Checking the shape of the identity matrix
ide.shape

(45, 45)

In [28]:
# Creating a 1D array from 0 to 98
arr = np.arange(99)

In [29]:
# Printing the array
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [30]:
# Reshaping the array into 3 rows and 33 columns
arr = arr.reshape(3,33)

In [31]:
# Printing the reshaped array
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [32]:
# Flattening the reshaped array back into 1D
arr = arr.ravel()

In [33]:
# Printing the flattened array
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [34]:
# Checking the shape of the flattened array
arr.shape

(99,)

In [35]:
# Creating a 2D list
x = [[1,2,3], [4,5,6], [7,1,0]]

In [36]:
# Converting the list into a numpy array
ar = np.array(x)

In [37]:
# Printing the array
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [38]:
# Calculating the sum along the columns (axis=0)
ar.sum(axis=0)

array([12,  8,  9])

In [39]:
# Calculating the sum along the rows (axis=1)
ar.sum(axis=1)

array([ 6, 15,  8])

In [40]:
# Transposing the array (rows become columns, and vice versa)
ar.T

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [41]:
# Accessing the flat iterator over the array
ar.flat

In [42]:
# Printing each item from the flat iterator
for item in ar.flat:
    print(item)

1
2
3
4
5
6
7
1
0


In [43]:
# Checking the number of dimensions of the array
ar.ndim

2

In [44]:
# Checking the total number of elements in the array
ar.size

9

In [45]:
# Checking the total number of bytes consumed by the array
ar.nbytes

72

In [46]:
# Creating a 1D array
one = np.array([1,3,4,634,2])

In [47]:
# Getting the index of the maximum element
one.argmax()

np.int64(3)

In [48]:
# Getting the indices that would sort the array
one.argsort()

array([0, 4, 1, 2, 3])

In [49]:
# Getting the index of the maximum element along axis=0
ar.argmax(axis=0)

array([2, 1, 1])

In [50]:
# Getting the index of the maximum element along axis=1
ar.argmax(axis=1)

array([2, 2, 0])

In [51]:
# Getting the index of the minimum element in the array
ar.argmin()

np.int64(8)

In [52]:
# Sorting the array along axis=1
ar.argsort(axis=1)

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]])

In [53]:
# Sorting the array along axis=0
ar.argsort(axis=0)

array([[0, 2, 2],
       [1, 0, 0],
       [2, 1, 1]])

In [54]:
# Flattening the array into 1D
ar.ravel()

array([1, 2, 3, 4, 5, 6, 7, 1, 0])

In [55]:
# Reshaping the array into a shape of (9,)
ar.reshape((9,))

array([1, 2, 3, 4, 5, 6, 7, 1, 0])

In [56]:
#printing the array 
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [57]:
# Creating a second 2D array
ar2 = np.array([[1, 2, 1],
       [4, 0, 6],
       [8, 1, 0]])

In [58]:
# Adding the two arrays element-wise
ar+ ar2

array([[ 2,  4,  4],
       [ 8,  5, 12],
       [15,  2,  0]])

In [59]:
# Multiplying the two arrays element-wise
ar * ar2

array([[ 1,  4,  3],
       [16,  0, 36],
       [56,  1,  0]])

In [60]:
# Calculating the square root of each element in the array
np.sqrt(ar)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 1.        , 0.        ]])

In [61]:
# Calculating the cube root of each element in the array
np.cbrt(ar)

array([[1.        , 1.25992105, 1.44224957],
       [1.58740105, 1.70997595, 1.81712059],
       [1.91293118, 1.        , 0.        ]])

In [62]:
# Calculating the sum of all elements in the array
ar.sum()

np.int64(29)

In [63]:
# Getting the maximum value in the array
ar.max()

np.int64(7)

In [64]:
# Getting the minimum value in the array
ar.min()

np.int64(0)

In [65]:
# printing the array 
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [66]:
# Getting the indices of elements greater than 5
np.where(ar>5)

(array([1, 2]), array([2, 0]))

In [67]:
# Checking the type of the output of np.where
type(np.where(ar>5))

tuple

In [68]:
# Counting the non-zero elements in the array
np.count_nonzero(ar)

8

In [69]:
# Getting the indices of non-zero elements in the array
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 1, 2, 2]), array([0, 1, 2, 0, 1, 2, 0, 1]))

In [70]:
# Setting an element at position [1, 2] to 0
ar[1,2] = 0

In [71]:
# Getting the indices of non-zero elements after modification
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 2, 2]), array([0, 1, 2, 0, 1, 0, 1]))

In [72]:
# Importing the sys module for system-specific parameters and functions
import sys

In [73]:
# Creating a Python list
py_ar = [0,4,55,2]

In [74]:
# Creating a numpy array from the Python list
np_ar = np.array(py_ar)

In [75]:

# Getting the size of each element in bytes and calculating the total memory size of the Python list
sys.getsizeof(1) * len(py_ar)

112

In [76]:
# Calculating the total memory size of the numpy array
np_ar.itemsize * np_ar.size

32

In [77]:
# Converting the numpy array back into a Python list
np_ar.tolist()

[0, 4, 55, 2]

In [78]:
# Returning the imaginary part of the elements of the array.
arr4 = np.array([1+2j, 3+4j, 5+6j])

In [79]:
# printing the complex elements in arr4
np.imag(arr4)

array([2., 4., 6.])

In [80]:
np.real(arr4)

array([1., 3., 5.])

In [81]:
# Correcting the array definition by putting the row lists inside a list
arrays = np.array([[1, 2, 3], 
                   [4, 5, 6], 
                   [7, 8, 9]])

In [82]:
# Returning the step size (in bytes) to move from one element to the next in each dimension of the array
arrays.strides

(24, 8)

In [83]:
# Importing the ctypes library for interacting with low-level C types in Python.
import ctypes

In [84]:
# Creating a 2D numpy array with two rows and two columns.
z = np.array([[0, 1],
       [2, 3]])

In [85]:
# Accessing the memory address (in bytes) where the array data is stored using ctypes.
z.ctypes.data

2056603243472